import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import "styles/globals.css";

export const metadata = {
  title: "Bag and Beyond",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="">
          <Nav />
        </header>
        <main className="relative">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
